config/routes.rb
Divelog::Application.routes.draw do
  resources :comments

  resources :dives

  devise_for :users
  get "welcome/index"

  root "welcome#index"

end

app/models/air_type.rb
class AirType < ActiveRecord::Base
	belongs_to :dive
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :dive
  belongs_to :user
end

app/models/dive.rb
class Dive < ActiveRecord::Base
	belongs_to :user
	has_one :air_type
	has_one :water_type
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 	has_many :dives
  has_many :comments
end

app/models/water_type.rb
class WaterType < ActiveRecord::Base
	belongs_to :dive
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
    @comment.dive_id = params[:dive_id]
    @comment.user_id = params[:user_id]
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comment }
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :dive_id, :comment_text)
    end
end

app/controllers/dives_controller.rb
class DivesController < ApplicationController
  before_action :set_dive, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /dives
  # GET /dives.json
  def index
    @user = User.find(current_user)
    @dives = Dive.where(:user_id => @user.id)
  end

  # GET /dives/1
  # GET /dives/1.json
  def show
    @comments = @dive.comments
  end

  # GET /dives/new
  def new
    @dive = Dive.new
  end

  # GET /dives/1/edit
  def edit
  end

  # POST /dives
  # POST /dives.json
  def create
    @dive = Dive.new(dive_params)
    @dive.user = current_user

    respond_to do |format|
      if @dive.save
        format.html { redirect_to @dive, notice: 'Dive was successfully created.' }
        format.json { render action: 'show', status: :created, location: @dive }
      else
        format.html { render action: 'new' }
        format.json { render json: @dive.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dives/1
  # PATCH/PUT /dives/1.json
  def update
    if dive_belongs_to_user
      respond_to do |format|
        if @dive.update(dive_params)
          format.html { redirect_to @dive, notice: 'Dive was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @dive.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /dives/1
  # DELETE /dives/1.json
  def destroy
    if dive_belongs_to_user
      @dive.destroy
      respond_to do |format|
        format.html { redirect_to dives_url }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dive
      @dive = Dive.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dive_params
      params.require(:dive).permit(:dive_number, :depth, :starting_pressure_group, :ending_pressure_group, :weight, :dive_time, :starting_air, :ending_air, :bottom_temperature)
    end

    def dive_belongs_to_user
      retval = false

      if @dive.user == current_user
        retval = true
      end

      return retval
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dives_helper.rb
module DivesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :comment_text %><br>
    <%= f.text_area :comment_text %>
  </div>
  <%= f.hidden_field :user_id, :value => @comment.user_id %>
  <%= f.hidden_field :dive_id, :value => @comment.dive_id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Dive</th>
      <th>Comment text</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_id %></td>
        <td><%= comment.dive_id %></td>
        <td><%= comment.comment_text %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Dive:</strong>
  <%= @comment.dive_id %>
</p>

<p>
  <strong>Comment text:</strong>
  <%= @comment.comment_text %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/dives/_form.html.erb
<%= form_for(@dive) do |f| %>
  <% if @dive.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dive.errors.count, "error") %> prohibited this dive from being saved:</h2>

      <ul>
      <% @dive.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%
    groups = []
    for group in 'A'...'Z'
      groups.push(group)
    end
  %>

  <div class="field">
    <%= f.label :dive_number %><br>
    <%= f.number_field :dive_number %>
  </div>
  <div class="field">
    <%= f.label "Depth in Feet" %><br>
    <%= f.number_field :depth %>
  </div>
  <div class="field">
    <%= f.label :starting_pressure_group %><br>
    <%= f.select :starting_pressure_group, options_for_select(groups, :selected => @dive.starting_pressure_group) %>
  </div>
  <div class="field">
    <%= f.label :ending_pressure_group %><br>
    <%= f.select :ending_pressure_group, options_for_select(groups, :selected => @dive.ending_pressure_group) %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.number_field :weight %>
  </div>
  <div class="field">
    <%= f.label :dive_time %><br>
    <%= f.number_field :dive_time %>
  </div>
  <div class="field">
    <%= f.label :starting_air %><br>
    <%= f.number_field :starting_air %>
  </div>
  <div class="field">
    <%= f.label :ending_air %><br>
    <%= f.number_field :ending_air %>
  </div>
  <div class="field">
    <%= f.label :bottom_temperature %><br>
    <%= f.number_field :bottom_temperature %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dives/edit.html.erb
<% if @dive.user == current_user %>
	<h1>Editing dive</h1>

	<%= render 'form' %>
	
	<%= link_to 'Show', @dive %> |
	<%= link_to 'Back', dives_path %>
<% else #TODO: come up with better wording %>
	<h2>Requested Dive is not yours</h2>
<% end %>

app/views/dives/index.html.erb
<h1>Your Dives Overview</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Dive Number</th>
      <th>Depth</th>
      <th>Location</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @dives.each do |dive| %>
      <tr data-link="<%= dive_path(dive) %>">
        <td><%= dive.dive_number %></td>
        <td><%= dive.depth %></td>
        <td>Somewhere Awesome</td>
        <td><%= link_to 'Show', dive %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dive', new_dive_path %>
<%= javascript_include_tag "dives" %>

app/views/dives/new.html.erb
<h1>New dive</h1>

<%= render 'form' %>

<%= link_to 'Back', dives_path %>

app/views/dives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dive number:</strong>
  <%= @dive.dive_number %>
</p>

<p>
  <strong>Depth:</strong>
  <%= @dive.depth %>
</p>

<p>
  <strong>Starting pressure group:</strong>
  <%= @dive.starting_pressure_group %>
</p>

<p>
  <strong>Ending pressure group:</strong>
  <%= @dive.ending_pressure_group %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @dive.weight %>
</p>

<p>
  <strong>Dive time:</strong>
  <%= @dive.dive_time %>
</p>

<p>
  <strong>Starting air:</strong>
  <%= @dive.starting_air %>
</p>

<p>
  <strong>Ending air:</strong>
  <%= @dive.ending_air %>
</p>

<p>
  <strong>Bottom temperature:</strong>
  <%= @dive.bottom_temperature %>
</p>

<h3>Comments</h3>
  <% @comments.each do |comment| %>
        <div class="comment well"><%= comment.comment_text %></div>
  <% end %>
<%= link_to 'Add Comment', new_comment_path(@dive) %>
<br />

<%= link_to 'Edit', edit_dive_path(@dive) %> |
<%= link_to 'Your Dives', dives_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Divelog" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Divelog</a>
          <div class="container nav-collapse">
            <ul class="nav">
            <% if user_signed_in? %>
                  <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Hello, <%= current_user.email %><span class="caret"></span></a>
                    <ul class="dropdown-menu">
                      <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                      <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
                    </ul>
                  </li>
                  <li><%= link_to "My Dives", "/dives"  %></li>
              <% else %>
                  <li><%= link_to "Login", new_user_session_path %></li>
              <% end %>
              <li><%= link_to "My Graphs", "/path2"  %></li>
              <li><%= link_to "Dive Buddies", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <input type="text" id="search" placeholder="Search..." />
              <ul class="nav nav-list">
                <li class="nav-header">Manage Trips</li>
                <li><%= link_to "Dive Shops", "/path1"  %></li>
                <li><%= link_to "Dive Resorts", "/path2"  %></li>
                <li><%= link_to "Current Specials", "/path3"  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/welcome/index.html.erb
<h1>BLOOOOOOOOP</h1>